mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include


from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('users/', include('users.urls'))
]

mysite/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path("login/", views.login_user, name="login"),
    path("registration/", views.registration_user, name="registration"),
    path("logout/", views.logout_user, name="logout")
]

mysite/users/models.py
from django.db import models

# Create your models here.

mysite/users/forms.py
from django import forms

class RegistrationForm(forms.Form):
    login = forms.CharField(label="login", max_length=128)
    email = forms.EmailField(label="email")
    password = forms.CharField(label="passsword", widget=forms.PasswordInput)

mysite/mysite/views.py
from django.http import HttpResponse
from django.shortcuts import render

def index(request):
    if request.user.is_authenticated:
        return render(request=request, template_name="templates/mysite/index.html", context={"is_authenticated": False})
    else:
        return render(request=request, template_name="templates/mysite/index.html", context={"is_authenticated": True})

mysite/users/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import reverse
from django.contrib.auth import authenticate
from django.contrib.auth import login, logout

from users.forms import RegistrationForm
from django.contrib.auth.models import User
def login_user(request):
    if request.method == "POST":
        user = authenticate(username=request.POST["login"], password=request.POST["password"])
        if user is not None:
            """
            Сохраняет идентификатор пользователя в сессии, используя фреймворк сессий Django
            """
            login(request=request, user=user)
            return HttpResponseRedirect(reverse('index'))
        else:
            return render(request, template_name="users/login.html", context={"error_message": "Invalid credentials"})
    else:
        return render(request=request, template_name="users/login.html")

def registration_user(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        
        if form.is_valid():
            login = form.cleaned_data["login"]
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]
            user = User.objects.create_user(username=login, email=email, password=password)
            user.save()
            return HttpResponseRedirect(reverse("users:login"))
    else:
        form = RegistrationForm()
    return render(request=request, template_name="users/registration.html", context={"form": form})

def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

mysite/mysite/templates/mysite/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Authorization app</h1>
    {% if is_authenticated %}
        <a href="{% url 'users:login' %}">Login</a> | <a href="{% url 'users:registration' %}">Registration</a>
    {% else %}
        <a href="{% url 'users:logout' %}">Logout</a>
    {% endif %}
</body>
</html>

mysite/users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <h1>Login</h1>
    <form action="" method="post">
        {% csrf_token %}
        {% if error_message %} <p style="color:red">{{ error_message }}</p> {% endif %}
        <input type="text" name="login" placeholder="Login" autocomplete="off"/>
        <input type="password" name="password" placeholder="Password" autocomplete="off"/>
        <input type="submit" value="Login" />
    </form>
</body>
</html>

mysite/users/templates/users/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration</title>
</head>
<body>
    <h1>Registration</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Registration" />
    </form>
</body>
</html>